orm:
  host: localhost
  port: 3306
  user: root
  # configure password in .env file to share with docker compose
  dbName: yaarxiv_prod
  connectionTimeout: 60000
  runMigrations: true
  debug: false
  highlight: false
jwtSecret: productionsecret
storage:
  type: minio
  connection:
    endPoint: localhost
    port: 9000
    useSSL: false
  # configure accesskey and secret key in .env file to share with docker compose
  bucketName: productionbucket
mail:
  host: <your mail service host>
  auth:
    user: <your mail username>
    pass: <your mail password>
frontendUrl: http://localhost:5000
