orm:
  host: localhost
  port: 3306
  user: root
  dbName: yaarxiv_prod
  connectionTimeout: 60000
  runMigrations: true
  debug: false
  highlight: false
jwtSecret: productionsecret
storage:
  connection:
    endPoint: localhost
    port: 9000
    useSSL: false
    accessKey: minio
    secretKey: miniominio
  bucketName: productionbucket
mail:
  host: <your mail service host>
  auth:
    user: <your mail username>
    pass: <your mail password>
frontendUrl: http://localhost:5000
