orm:
  type: mysql
  host: localhost
  port: 3306
  dbName: yaarxiv_test_${NODE_ENV}_${JEST_WORKER_ID}
  user: root
  password: dbfordev
  synchronize: true
  dropSchema: true
logger:
  level: error
  prettyPrint: true
storage:
  type: fs
  path: testupload/${JEST_WORKER_ID}
