version: "3"
services:

  nginx:
    image: nginx:stable-alpine
    container_name: yaarxiv_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static/
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - frontend
      - backend

  db:
    image: mysql:8
    container_name: yaarxiv_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - "./db:/var/lib/mysql"
    ports:
      - 3306:3306

  frontend:
    image: yaarxiv/frontend
    container_name: yaarxiv_frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        USE_MOCK: "0"
    ports:
      - "3000:3000"
    environment:
      - USE_MOCK="0"
      - SERVER_API_ROOT="http://backend:5000"
      - CLIENT_API_ROOT="/api"
      - STATIC_FILE_ROOT="/static"

  backend:
    image: yaarxiv/backend
    container_name: yaarxiv_backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - "./backend/config/production.ts:/dist/config/production.ts"
      - "./backend/distdb:/dist/db"
      - "./backend/distupload:/dist/upload"
    ports:
      - "5000:5000"
