version: "3"
services:

  nginx:
    image: nginx:stable-alpine
    container_name: yaarxiv_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static/
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - frontend
      - backend

  db:
    image: mysql:8
    container_name: yaarxiv_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - "${YAARXIV_FILES_ROOT}/db:/var/lib/mysql"
    ports:
      - 3306:3306

  frontend:
    image: yaarxiv/frontend
    container_name: yaarxiv_frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        USE_MOCK: "0"
    ports:
      - "3000:3000"
    environment:
      - USE_MOCK="0"
      - SERVER_API_ROOT=http://backend:5000
      - CLIENT_API_ROOT=/api
      - STATIC_FILE_ROOT=/static

  backend:
    image: yaarxiv/backend
    container_name: yaarxiv_backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MINIO_ACCESSKEY: ${MINIO_ACCESSKEY}
      MINIO_SECRETKEY: ${MINIO_SECRETKEY}
    volumes:
      - "./backend/config/production.yml:/dist/config/production.yml"
    ports:
      - "5000:5000"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESSKEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRETKEY}
    volumes:
      - "${YAARXIV_FILES_ROOT}/minio:/data"
    ports:
      - "9001:9001"
