version: "3"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: dbfordev
    volumes:
      - "./db:/var/lib/mysql"
    ports:
      - 3306:3306
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        USE_MOCK: "0"
    ports:
      - "80:3000"
    environment:
      - API_ROOT=http://localhost:5000
  backend:
    image: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - "./backend/config/production.ts:/dist/config/production.ts"
      - "./backend/distdb:/dist/db"
      - "./backend/distupload:/dist/upload"
    ports:
      - "5000:3000"
