version: "3"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: dbfordev
    volumes:
      - "./db:/var/lib/mysql"
    ports:
      - 3306:3306

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniominio
    volumes:
      - ./upload:/data
    ports:
      - 9000:9000
      - 9001:9001
