import { UserRole } from "../auth/login";
import { ApiProps } from "../utils/apiProps";
import { Endpoint } from "../utils/schema";

export interface UpdateArticleSchema {
  path: {
    /** The original articleId. */
    articleId: number;
  },
  body: {
    /** The file token generated by uploading the PDF file. */
    pdfToken?: number;
    /**
     * The title of the article.
     * @maxLength 100
     */
    title?: string;
    /** The authors of the article. */
    authors?: string[];
    /** The keywords of the article. */
    keywords?: string[];
    /**
     * The abstract of the article.
     * @maxLength 2000
     */
    abstract?: string;
    /**
     * Link to code.
     * Should pass validation from utils/codeLink.ts
     * @format uri
     */
    codeLink?: string;
  };
  responses: {
    /** The update is successful. */
    201: {
      /**
       * The new revision number.
       * @type {integer}
       */
      revisionNumber: number;
    },
    /** Not logged in. */
    401: null;
    /** The user is not the owner. */
    403: null;
    /** The article is not found. */
    404: null;
  }
}

export const apiProps: ApiProps = {
  requiredRoles: [UserRole.Admin, UserRole.User],
};

export const endpoint = {
  url: "/articles/:articleId",
  method: "PUT",
} as Endpoint<UpdateArticleSchema>;
