export const endpoint = {
  url: "/articles/:articleId",
  method: "PUT",
} as const;

export interface UpdateArticleSchema {
  path: {
    /** The original articleId. */
    articleId: string;
  },
  body: {
    /** The file token generated by uploading the PDF file. */
    pdfToken?: string;
    /**
     * The title of the article.
     * @maxLength 100
     */
    title?: string;
    /** The authors of the article. */
    authors?: string[];
    /** The keywords of the article. */
    keywords?: string[];
    /**
     * The abstract of the article.
     * @maxLength 2000
     */
    abstract?: string;
    /**
     * Link to code
     * @format uri
     */
    codeLink?: string;
  };
  responses: {
    /** The update is successful. */
    201: {
      /**
       * The new revision number.
       * @type {integer}
       */
      revisionNumber: number;
    },
    /** Not logged in. */
    401: {

    }
    /** The user is not the owner. */
    403: {
    }
    /** The article is not found. */
    404: {

    }
  }
}
