export const endpoint = {
  url: "/articles",
  method: "POST",
} as const;

/** Upload an new article into the platform. */
export interface UploadArticleSchema {
  body: {
    /** The file token generated by uploading the PDF file. */
    pdfToken: string;
    /**
     * The title of the article.
     * @maxLength 100
     */
    title: string;
    /** The authors of the article. */
    authors: string[];
    /** The keywords of the article. */
    keywords: string[];
    /**
     * The abstract of the article.
     * @maxLength 2000
     */
    abstract: string;
  };
  responses: {
    /** The upload is successful. */
    201: {
      /** The id of the new article. */
      id: string;
    },
  }
}
