version: "3"
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dbforproduction
    volumes:
      - "./db:/var/lib/mysql"
    ports:
      - 3306:3306
  frontend:
    image: yaarxiv/frontend
    restart: always
    ports:
      - "80:3000"
  backend:
    image: yaarxiv/backend
    restart: always
    volumes:
      - "./production.ts:/dist/config/production.ts"
      - "./prod.db:/dist/db.db"
      - "./upload:/dist/upload"
    ports:
      - "3000:3000"
