import { UserRole } from "../auth/login";
import { ApiProps } from "../utils/apiProps";
import { Endpoint } from "../utils/schema";
import { ArticleId, ArticleInfo } from "./models";

export interface UpdateArticleSchema {
  path: {
    /** The original articleId. */
    articleId: ArticleId;
  },

  body: {
    /** The file token generated by uploading the PDF file. */
    pdfToken?: number;
  } & ArticleInfo;

  responses: {
    /** The update is successful. */
    201: {
      /**
       * The new revision number.
       * @type {integer}
       */
      revisionNumber: number;
    },
    /** Not logged in. */
    401: null;
    /** The user is not the owner. */
    403: null;
    /** The article is not found. */
    404: null;
  }
}

export const props: ApiProps = {
  requiredRoles: [UserRole.Admin, UserRole.User],
};

export const endpoint = {
  url: "/articles/:articleId",
  method: "PUT",
} as Endpoint<UpdateArticleSchema>;
