import { UserRole } from "../auth/login";
import { ApiProps } from "../utils/apiProps";
import { ArticleNotFoundResponse, ErrorResponse } from "../utils/error";
import { Endpoint } from "../utils/schema";
import { ArticleId, ArticleInfo } from "./models";

export interface UpdateArticleSchema {
  path: {
    /** The original articleId. */
    articleId: ArticleId;
  },

  body: {
    /** The file token generated by uploading the PDF file. */
    pdfToken?: number;
  } & ArticleInfo;

  responses: {
    /** The update is successful. */
    201: {
      /**
       * The new revision number.
       * @type {integer}
       */
      revisionNumber: number;
    },

    400: ErrorResponse<"ARTICLEINFO_I18N_CONSTRAINTS" | "CODE_LINK_INVALID" | "FILE_TOKEN_INVALID">;

    /**
     * notAuthor: Not the author of the article
     * retracted: the article has been retracted.
     */
    403: ErrorResponse<"NOT_AUTHOR" | "ARTICLE_RETRACTED">;

    /** The article is not found. */
    404: ArticleNotFoundResponse;
  }
}

export const props: ApiProps = {
  requiredRoles: [UserRole.Admin, UserRole.User],
};

export const endpoint = {
  url: "/articles/:articleId",
  method: "PUT",
} as Endpoint<UpdateArticleSchema>;
