import { UserRole } from "../auth/login";
import { ApiProps } from "../utils/apiProps";
import { ErrorResponse } from "../utils/error";
import { Endpoint } from "../utils/schema";
import { ArticleInfo } from "./models";

export const ARTICLE_ABSTRACT_LENGTH_LIMIT = 2000;

/** Upload an new article into the platform. */
export interface UploadArticleSchema {

  body: {
    /** The file token generated by uploading the PDF file. */
    pdfToken: number;
  } & ArticleInfo;

  responses: {
    /** The upload is successful. */
    201: {
      /** The id of the new article. */
      id: number;
    },

    400: ErrorResponse<"ARTICLEINFO_I18N_CONSTRAINTS" | "CODE_LINK_INVALID" | "FILE_TOKEN_INVALID">;
  }
}

export const props: ApiProps = {
  requiredRoles: [UserRole.User],
};

export const endpoint = {
  url: "/articles",
  method: "POST",
} as Endpoint<UploadArticleSchema>;
