import { UserRole } from "../auth/login";
import { ApiProps } from "../utils/apiProps";
import { Endpoint } from "../utils/schema";

/** Upload an new article into the platform. */
export interface UploadArticleSchema {
  body: {
    /** The file token generated by uploading the PDF file. */
    pdfToken: number;
    /**
     * The title of the article.
     * @maxLength 100
     */
    title: string;
    /** The authors of the article. */
    authors: string[];
    /** The keywords of the article. */
    keywords: string[];
    /**
     * The abstract of the article.
     * @maxLength 2000
     */
    abstract: string;
    /**
     * Link to code.
     * Should pass validation from utils/codeLink.ts
     * @format uri
     */
    codeLink?: string;
  };
  responses: {
    /** The upload is successful. */
    201: {
      /** The id of the new article. */
      id: number;
    },
  }
}

export const props: ApiProps = {
  requiredRoles: [UserRole.User],
};

export const endpoint = {
  url: "/articles",
  method: "POST",
} as Endpoint<UploadArticleSchema>;
