name: Build and Publish backend

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - backend/**
      - api/**

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:lts-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
        working-directory: backend

      - name: Run tests with coverage
        run: npm run test:coverage
        working-directory: backend

      - name: Publish tests coverage result to coveralls
        uses: coverallsapp/github-action@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: backend/coverage/lcov.info
          base-path: backend
        # https://github.com/coverallsapp/github-action/issues/50
        env:
          COVERALLS_FLAG_NAME: Backend Integration

  publish_to_registry:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish backend image
        uses: docker/build-push-action@v1
        with:
          repository: yaarxiv/backend
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true
          # tag_with_sha: true
          dockerfile: backend/Dockerfile

  request-deployment:
    runs-on: ubuntu-latest
    needs: publish_to_registry
    steps:
      - uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.DEPLOY_AGENT_URL }}
          method: POST
          contentType: "text/plain"
          data: "backend"
          customHeaders: '{"x-deploy-agent-key": "${{ secrets.DEPLOY_AGENT_KEY }}"}'

