name: Build and Publish backend

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - backend/**
      - api/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - name: Install dependencies
        run: npm ci
        working-directory: backend

      - name: Run tests with coverage
        run: npm run test:coverage
        working-directory: backend

      - name: Publish tests coverage result to coveralls
        uses: coverallsapp/github-action@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: backend/coverage/lcov.info
          base-path: backend
        # https://github.com/coverallsapp/github-action/issues/50
        env:
          COVERALLS_FLAG_NAME: Backend Integration

      - name: Build and publish backend image
        uses: docker/build-push-action@v1
        with:
          repository: yaarxiv/backend
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true
          # tag_with_sha: true
          dockerfile: backend/Dockerfile
