name: Build and Publish frontend

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - frontend/**
      - api/**

jobs:
  publish-to-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: frontend/Dockerfile
          push: true
          tags: |
            yaarxiv/frontend:latest

  request-deployment:
    runs-on: ubuntu-latest
    needs: publish-to-registry
    steps:
      - uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.DEPLOY_AGENT_URL }}
          method: POST
          contentType: "text/plain"
          # data: '"frontend"'
          customHeaders: '{"x-deploy-agent-key": "${{ secrets.DEPLOY_AGENT_KEY }}"}'
