name: Build and Publish frontend

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - frontend/**
      - api/**

jobs:
  publish_to_registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and publish frontend image
        uses: docker/build-push-action@v1
        with:
          repository: yaarxiv/frontend
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true
          # tag_with_sha: true
          dockerfile: frontend/Dockerfile
          build_args: API_ROOT=${{ secrets.API_ROOT }}

  request-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.DEPLOY_AGENT_URL }}
          method: POST
          contentType: "text/plain"
          data: "frontend"
          customHeaders: '{"x-deploy-agent-key": ${{ secrets.DEPLOY_AGENT_KEY }}'
