name: Build and Publish mock frontend

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - frontend/**
      - api/**

jobs:
  publish-to-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and publish frontend image
        uses: docker/build-push-action@v1
        with:
          repository: yaarxiv/frontend_mock
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true
          # tag_with_sha: true
          dockerfile: frontend/Dockerfile
          build-args: |
            USE_MOCK=1
          
